syntax = "proto3";

package account;

option go_package = "qpayflow/api/proto/account;account";

service AccountService {
  rpc GetAccount (GetAccountRequest) returns (AccountResponse);
  rpc Transfer (TransferRequest) returns (TransferResponse);
}

message GetAccountRequest {
  string id = 1;
}

message AccountResponse {
  string id = 1;
  string owner_id = 2;
  string currency = 3;
  double balance = 4;
  int64 version = 5;
  string created_at = 6;
  string updated_at = 7;
}

message TransferRequest {
  string transaction_id = 1;
  string from_account_id = 2;
  string to_account_id = 3;
  double amount = 4;
  string currency = 5;
  string description = 6;
  string lock_strategy = 7; // "pessimistic" or "redis"
}

message TransferResponse {
  string status = 1; // SUCCESS or FAILED
  string transaction_id = 2;
  string error_message = 3;
}
