syntax = "proto3";

package payment;

option go_package = "qpayflow/api/proto/payment;payment";

service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (PaymentResponse);
  rpc GetPayment (GetPaymentRequest) returns (PaymentResponse);
}

message CreatePaymentRequest {
  string idempotency_key = 1;
  int64 user_id = 2;
  double amount = 3;
  string currency = 4;
  string payment_method = 5;
}

message GetPaymentRequest {
  string id = 1;
}

message PaymentResponse {
  string id = 1;
  string idempotency_key = 2;
  int64 user_id = 3;
  double amount = 4;
  string currency = 5;
  string status = 6;
  string payment_method = 7;
  string created_at = 8;
  string updated_at = 9;
}
