syntax = "proto3";

package payment;

option go_package = "qpayflow/api/proto/payment;payment";

service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (PaymentResponse);
  rpc GetPayment (GetPaymentRequest) returns (PaymentResponse);
}

message CreatePaymentRequest {
  string idempotency_key = 1;
  string source_account_id = 2;
  string target_account_id = 3;
  double amount = 4;
  string currency = 5;
}

message GetPaymentRequest {
  string id = 1;
}

message PaymentResponse {
  string id = 1;
  string idempotency_key = 2;
  string source_account_id = 3;
  string target_account_id = 4;
  double amount = 5;
  string currency = 6;
  string status = 7; // PENDING, PROCESSING, SUCCESS, FAILED
  string created_at = 8;
  string updated_at = 9;
}
