apiVersion: v1
kind: Secret
metadata:
  name: qpayflow-secrets
  namespace: qpayflow
  labels:
    app.kubernetes.io/name: qpayflow
type: Opaque
stringData:
  POSTGRES_USER: "qpayflow"
  POSTGRES_PASSWORD: "qpayflow_secret"
  REDIS_PASSWORD: ""
  JWT_SECRET: "qpayflow_super_secret_jwt_key_32bytes!"
