server:
  port: 8002

postgres:
  host: "localhost"
  port: 5432
  user: "qpayflow"
  password: "qpayflow_secret"
  dbname: "qpayflow_db"
  sslmode: "disable"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

kafka:
  brokers:
    - "localhost:9092"
  payment_events_topic: "payment-events"
  account_group_id: "account-service-group"
