apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: qpayflow
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: qpayflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
